"""prepare.py — the immutable anti-cheat evaluator of the autoresearch loop.

Do NOT edit this file (see program.md, section *Experimentation*). It owns the
fixed constants, the corpus, the tokenizer, the dataloader, and — most
importantly — the ground-truth metric `evaluate_bpb`. The agent's only job is
to make `val_bpb` as low as possible by editing ONLY train.py, and train.py
must import evaluate_bpb from here, never redefine it.

SC5 (domain adaptation): to port this template to a new domain, change only the
DATA section below (corpus constants + tokenizer + dataloader) and the notes in
program.md. The metric and the loop stay intact.

Stdlib only — no numpy, no torch.
"""

import math

# ---------------------------------------------------------------------------
# Fixed constants
# ---------------------------------------------------------------------------
TIME_BUDGET = 300  # seconds — fixed wall-clock training budget (SC2, SC6)
MAX_SEQ_LEN = 32
BATCH_SIZE = 16

# ---------------------------------------------------------------------------
# Data side — the ONLY section that changes when porting to a new domain (SC5)
# ---------------------------------------------------------------------------
# A tiny deterministic char-level corpus: enough structure for a meaningful
# val_bpb baseline, small enough to train in milliseconds under any budget.
TRAIN_TEXT = (
    "the quick brown fox jumps over the lazy dog. "
    "pack my box with five dozen liquor jugs. "
    "how vexingly quick daft zebras jump. "
) * 60

VAL_TEXT = (
    "sphinx of black quartz judge my vow. "
    "the five boxing wizards jump quickly."
)

# Special tokens. Token id 0 = <pad> (masked in evaluation).
_PAD, _BOS, _EOS = 0, 1, 2
SPECIAL_TOKENS = {"<pad>": _PAD, "<bos>": _BOS, "<eos>": _EOS}
MASK_IDS = frozenset((_PAD,))  # special tokens are masked in the metric


def _char_tokens(text):
    """Split a string into single-character tokens (char-level model)."""
    return list(text)


def tokenizer():
    """SC5 data hook — the (vocab, tokenize) pair for the domain.

    Returns:
        vocab:    list of token strings; index i is token id i.
        tokenize: callable text -> list[int] (token ids).
    """
    specials = [tok for tok in SPECIAL_TOKENS]
    chars = sorted({c for c in TRAIN_TEXT + VAL_TEXT})
    vocab = specials + chars
    index = {tok: i for i, tok in enumerate(vocab)}

    def tokenize(text):
        return [index[tok] for tok in _char_tokens(text)]

    return vocab, tokenize


# Token id -> utf-8 byte length. Built once (ASCII char corpus => 1 byte each).
VOCAB, TOKENIZE = tokenizer()
TOKEN_BYTES = {i: len(tok.encode("utf-8")) for i, tok in enumerate(VOCAB)}


def dataloader(text, batch_size=BATCH_SIZE, seq_len=MAX_SEQ_LEN):
    """SC5 data hook — yield (x_ids, y_ids) batches for a corpus string.

    Sliding-window char n-grams: x is a context window, y is the shifted
    target window. Yields batches of (list[int], list[int]) pairs.
    """
    ids = TOKENIZE(text)
    windows = []
    for i in range(len(ids) - seq_len):
        x = ids[i:i + seq_len]
        y = ids[i + 1:i + 1 + seq_len]
        windows.append((x, y))
    for start in range(0, len(windows), batch_size):
        yield windows[start:start + batch_size]


def _byte_len(token_bytes, token_id) -> int:
    """Resolve the utf-8 byte length of a token id (mapping or callable)."""
    if callable(token_bytes):
        return int(token_bytes(token_id))
    return int(token_bytes[token_id])


def evaluate_bpb(logits, target_ids, token_bytes, mask_ids=MASK_IDS):
    """Ground-truth metric (SC4): bits per byte over a validation batch.

        total per-token cross-entropy in nats
    -------------------------------------------------
        log(2) x total utf-8 byte length of targets

    Special tokens (mask_ids) are excluded from both the numerator and the
    byte-length denominator. Lower is better. This is the metric train.py must
    minimise — it is the anti-cheat ground truth and must never be redefined.

    Args:
        logits:      iterable of per-position logit vectors (len V each).
        target_ids:  iterable of target token ids (same length as logits).
        token_bytes: mapping {token_id: byte_length} or callable id -> length.
        mask_ids:    frozenset of special token ids to mask.
    """
    if len(logits) != len(target_ids):
        raise ValueError(
            "evaluate_bpb: logits and target_ids must have equal length, "
            "got {} and {}".format(len(logits), len(target_ids)))
    total_nats = 0.0
    total_bytes = 0
    for lg, tid in zip(logits, target_ids):
        if tid in mask_ids:
            continue
        # numerically-safe softmax over the position's logits
        m = max(lg)
        exp_sum = 0.0
        for x in lg:
            exp_sum += math.exp(x - m)
        p_target = math.exp(lg[tid] - m) / exp_sum
        total_nats += -math.log(p_target)
        total_bytes += _byte_len(token_bytes, tid)
    if total_bytes <= 0:
        raise ValueError("evaluate_bpb: no countable target bytes (all masked?)")
    return total_nats / (math.log(2.0) * total_bytes)


if __name__ == "__main__":
    v, tok = tokenizer()
    print("prepare.py OK — TIME_BUDGET={}s, vocab_size={}".format(TIME_BUDGET, len(v)))
